version: '3'

services:
  api:
    container_name: limpsys-api
    build:
      context: api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: npm run dev
    tty: true
    ports:
      - 3333:3333
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - ./api:/app
    depends_on:
      - postgres
  postgres:
    container_name: limpsys-pg
    image: postgres:16
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data: