version: '3'

services:
  api:
    container_name: limpsys-api
    build:
      context: api
      dockerfile: Dockerfile.dev
    image: node:20
    restart: unless-stopped
    command: npm run dev
    tty: true
    ports:
      - 3333:3333
    volumes:
      - api_data:/app
    depends_on:
      - postgres
  postgres:
    container_name: limpsys-pg
    image: postgres:16
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
  api_data: